### ISSUE TITLE
Weird syntax error when installing on Ubuntu

### ISSUE THREAD

**Issue by pnoeric** [tldr-pages/tldr-node-client#158]
## Expected behaviour
I thought I'd get tldr...

## Actual behaviour
I installed it with `npm install -g tldr`

and then this:

```
root@Eric:/home/owner# tldr
/usr/local/lib/node_modules/tldr/bin/tldr:34
program.on('--help', () => {
                      ^
SyntaxError: Unexpected token )
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:902:3

```

## Environment
- Ubuntu 14
- node v0.10.25
- npm v1.3.10

No idea what's going on, how can I fix this and get tldr?

Thanks, Eric

**Comment by agnivade** [comment]
Node 0.10 is no longer supported. Please upgrade to an LTS version.

**Comment by pnoeric** [comment]
Thanks, that was it.
