### ISSUE TITLE
Error when updating from my forked tldr-pages repo

### ISSUE THREAD

**Issue by brpaz** [tldr-pages/tldr-node-client#159]
## Expected behaviour
Should be able to use a custom repository and be able to update the index.

## Actual behaviour

An error occurred when running command ```tldr --update```

## Log, debug output
```
Error: Cannot update from https://github.com/brpaz/tldr/archive/master.zip
    at Extract.extractor.on (/home/bruno/.nvm/versions/node/v8.7.0/lib/node_modules/tldr/lib/remote.js:44:12)
    at emitOne (events.js:115:13)
    at Extract.emit (events.js:210:7)
    at Parse.<anonymous> (/home/bruno/.nvm/versions/node/v8.7.0/lib/node_modules/tldr/node_modules/unzip2/lib/extract.js:28:10)
    at emitOne (events.js:115:13)
    at Parse.emit (events.js:210:7)
    at InflateRaw.<anonymous> (/home/bruno/.nvm/versions/node/v8.7.0/lib/node_modules/tldr/node_modules/unzip2/lib/parse.js:141:20)
    at emitOne (events.js:120:20)
    at InflateRaw.emit (events.js:210:7)
    at InflateRaw.zlibOnError (zlib.js:155:8)
```

## Environment
- Linux Mint 18.2
- Node 8.7.0

Here is my .tldrcrc file:

```
{
  "repository": "brpaz/tldr",
  "theme": "simple"
}
```

**Comment by agnivade** [comment]
Thanks. This code path wasn't really well tested. There is some documentation update and some code updates that needs to be done. 

Essentially, you need to have the tldr.zip file in the target repo. The documentation is incorrect in saying that it takes from a forked tldr repo. It actually takes the file from the tldr.github.io repo.
