### ISSUE TITLE
Error: Cannot update from http://tldr-pages.github.io/assets/tldr.zip

### ISSUE THREAD

**Issue by GRiMe2D** [tldr-pages/tldr-node-client#181]
## Expected behaviour
Updates the cache and shows the page

## Actual behaviour
Tries to update, but crashes with error

## Log, debug output
Clean install.
```
$ npm install -g tldr
npm WARN deprecated node-uuid@1.4.8: Use uuid module instead
/usr/local/bin/tldr -> /usr/local/lib/node_modules/tldr/bin/tldr

> webworker-threads@0.7.13 install /usr/local/lib/node_modules/tldr/node_modules/webworker-threads
> node-gyp rebuild

gyp WARN install got an error, rolling back install
gyp ERR! configure error 
gyp ERR! stack Error: 403 response downloading https://nodejs.org/download/release/v7.10.0/node-v7.10.0-headers.tar.gz
gyp ERR! stack     at Request.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/install.js:210:14)
gyp ERR! stack     at emitOne (events.js:101:20)
gyp ERR! stack     at Request.emit (events.js:191:7)
gyp ERR! stack     at Request.onRequestResponse (/usr/local/lib/node_modules/npm/node_modules/request/request.js:986:10)
gyp ERR! stack     at emitOne (events.js:96:13)
gyp ERR! stack     at ClientRequest.emit (events.js:191:7)
gyp ERR! stack     at HTTPParser.parserOnIncomingClient (_http_client.js:522:21)
gyp ERR! stack     at HTTPParser.parserOnHeadersComplete (_http_common.js:99:23)
gyp ERR! stack     at TLSSocket.socketOnData (_http_client.js:411:20)
gyp ERR! stack     at emitOne (events.js:96:13)
gyp ERR! System Darwin 16.7.0
gyp ERR! command "/usr/local/Cellar/node/7.10.0/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/local/lib/node_modules/tldr/node_modules/webworker-threads
gyp ERR! node -v v7.10.0
gyp ERR! node-gyp -v v3.5.0
gyp ERR! not ok 
... (dependency tree)
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: webworker-threads@0.7.13 (node_modules/tldr/node_modules/webworker-threads):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: webworker-threads@0.7.13 install: `node-gyp rebuild`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1

$ tldr tar
Page not found. Updating cache ..
Error: Cannot update from http://tldr-pages.github.io/assets/tldr.zip
    at Extract.extractor.on (/usr/local/lib/node_modules/tldr/lib/remote.js:24:12)
    at emitOne (events.js:101:20)
    at Extract.emit (events.js:191:7)
    at Parse.<anonymous> (/usr/local/lib/node_modules/tldr/node_modules/unzip2/lib/extract.js:28:10)
    at emitOne (events.js:96:13)
    at Parse.emit (events.js:191:7)
    at /usr/local/lib/node_modules/tldr/node_modules/unzip2/lib/parse.js:64:12
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)
```

## Environment
- Operating system - OSX
- NodeJS version - v7.10.0
- NPM version - 4.2.0

**Comment by agnivade** [comment]
It seems you have 2 issues here ?

Is it that npm installation throws and error or the cache does not get updated ?

**Comment by agnivade** [comment]
ping @GRiMe2D - Is this still an issue for you ?

**Comment by GRiMe2D** [comment]
Thanks, today tried again, and now `tldr` works as expected
