### ISSUE TITLE
tldr install by yarn can not run

### ISSUE THREAD

**Issue by Honghe** [tldr-pages/tldr-node-client#209]
## Expected behaviour
tldr installed and can work.

## Actual behaviour
tldr installed and but not work.
reinstall tldr still the same.

## Log, debug output
```
 yarn global add tldr
yarn global v1.6.0
[1/4] Resolving packages...
warning tldr > unzip2 > fstream > graceful-fs@3.0.11: please upgrade to graceful-fs 4 for compatibility with current and future versions of Node.js
warning tldr > unzip2 > fstream > graceful-fs > natives@1.1.3: This module relies on Node.js's internals and will break at some point. Do not use it, and update to graceful-fs@4.x.
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
success Installed "tldr@3.2.1" with binaries:
      - tldr
Done in 5.56s.
➜  ~ tldr
/home/iron/.config/yarn/global/node_modules/natural/lib/natural/classifiers/classifier.js:32
    if (e.code !== 'MODULE_NOT_FOUND') throw e;
                                       ^
Error: The module '/home/iron/.config/yarn/global/node_modules/webworker-threads/build/Release/WebWorkerThreads.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 46. This version of Node.js requires
NODE_MODULE_VERSION 57. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
    at Object.Module._extensions..node (module.js:664:18)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at bindings (/home/iron/.config/yarn/global/node_modules/bindings/bindings.js:81:44)
    at Object.<anonymous> (/home/iron/.config/yarn/global/node_modules/webworker-threads/index.js:1:105)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
➜  ~ node --version
v8.9.3
➜  ~ yarn version
yarn version v1.6.0
error Couldn't find a package.json file in "/home/iron"
info Visit https://yarnpkg.com/en/docs/cli/version for documentation about this command.
➜  ~ yarn global dir
/home/iron/.config/yarn/global
```
## Environment
- Operating system - ubuntu 16.04.4
- NodeJS version v8.9.3

**Comment by agnivade** [comment]
Please see https://github.com/tldr-pages/tldr-node-client#installation-issues. 3rd point.

**Comment by Honghe** [comment]
Thanks! Got it by following:
```
yarn global add node-gyp
yarn global add webworker-threads
yarn global add tldr
```
But I still have some doubt. Before the above command fixing the problem, I have rm all global package by npm and yarn, checked by the following commands, and reinstall tldr. 
```
yarn global list
// npm is deleted
```
By the dependencies relationship `tldr -> webworker-threads ->node-gyp`, yarn should auto install `node-gyp` and build `webworker-threads` before install tldr. But from the phenomenon I report, it seems the dependency manage system did not do that?

**Comment by agnivade** [comment]
I think in your system, webworker-threads was already built before from seeing the error message. Hence, yarn did not re-build it. I am not familiar with inner workings of node-gyp.
