### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by 17-12-20-ll** [tldr-pages/tldr-node-client#252]
jobs@jobs-911:~$ tldr tar
Page not found. Updating cache ..
Error: Cannot update from http://tldr-pages.github.io/assets/tldr.zip
    at Extract.extractor.on (/snap/tldr/162/lib/node_modules/tldr/lib/remote.js:24:12)
    at emitOne (events.js:101:20)
    at Extract.emit (events.js:188:7)
    at Parse.<anonymous> (/snap/tldr/162/lib/node_modules/tldr/node_modules/unzip2/lib/extract.js:28:10)
    at emitOne (events.js:96:13)
    at Parse.emit (events.js:188:7)
    at /snap/tldr/162/lib/node_modules/tldr/node_modules/unzip2/lib/parse.js:64:12
    at runCallback (timers.js:666:20)
    at tryOnImmediate (timers.js:639:5)
    at processImmediate [as _immediateCallback] (timers.js:611:5)

Please tell me why？
thanks！

**Comment by 17-12-20-ll** [comment]
my email 13111856135@163.com

**Comment by agnivade** [comment]
Are you able to download the zip file manually ?

**Comment by agnivade** [comment]
Hello @17-12-20-ll - I will close this issue due to inactivity. Please feel free to comment on it if you want to debug this further. Thanks.
