### ISSUE TITLE
tldr got additional error log message

### ISSUE THREAD

**Issue by downdemo** [tldr-pages/tldr-node-client#322]
## Expected behaviour
run `tldr` to see help info.

## Actual behaviour
It works, but got addtional log message behind help info.

## Log, debug output
This is additional log message.

```
/usr/lib/node_modules/tldr/bin/tldr:116
p.catch((err) => {
  ^

TypeError: Cannot read property 'catch' of null
    at Object.<anonymous> (/usr/lib/node_modules/tldr/bin/tldr:116:3)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47
```

## Environment
- Operating system - Ubuntu 18.04.5 LTS (Bionic Beaver) Server install image
- NodeJS version - v14.15.1
- NPM version - 6.14.9

## Fix

I see this file, `/usr/lib/node_modules/tldr/bin/tldr`

```js
112 if (p === null) {
113   program.outputHelp();
114   process.exitCode = 1;
115 }
116 p.catch((err) => {
117   console.error(err);
118   process.exitCode = 1;
119 });
```

This problem may be fixed easily, it works for me.

```js
112 if (p === null) {
113   program.outputHelp();
114   process.exitCode = 1;
115 } else {
116   p.catch((err) => {
117     console.error(err);
118     process.exitCode = 1;
119   });
120 }
```

**Comment by agnivade** [comment]
Yep, just merged https://github.com/tldr-pages/tldr-node-client/pull/321. Thanks for reporting!
