### ISSUE TITLE
TLDR update error

### ISSUE THREAD

**Issue by shev85** [tldr-pages/tldr-node-client#445]
tldr --update
⠧ Updating.../usr/local/lib/node_modules/tldr/node_modules/adm-zip/adm-zip.js:62
            throw Utils.Errors.INVALID_FILENAME();
            ^

Error: ADM-ZIP: Invalid filename
    at Object.INVALID_FILENAME (/usr/local/lib/node_modules/tldr/node_modules/adm-zip/util/errors.js:56:16)
    at new module.exports (/usr/local/lib/node_modules/tldr/node_modules/adm-zip/adm-zip.js:62:32)
    at WriteStream.<anonymous> (/usr/local/lib/node_modules/tldr/lib/remote.js:32:21)
    at WriteStream.emit (node:events:529:35)
    at finish (node:internal/streams/writable:748:10)
    at finishMaybe (node:internal/streams/writable:733:9)
    at afterWrite (node:internal/streams/writable:507:3)
    at onwrite (node:internal/streams/writable:480:7)
    at node:internal/fs/streams:465:5
    at node:internal/fs/streams:421:7

Node.js v18.19.1

on ubuntu 24.04，dosen’t work，how to fix it?

**Comment by kbdharun** [comment]
Thanks for reporting the issue, can you try running `tldr --clear-cache` then run `tldr --update` to see if it fixes the issue?

**Comment by ycyin** [comment]
@kbdharun Hi! I used `nvm` to switch node versions 18, 20, 22 and none of them worked. Trying to use `tldr --clear-cach` and then `tldr --update` is the same issue.
```
[ttt@Ubuntu24.04 ~ (⎈|default]$ tldr --update
⠼ Updating.../home/ttt/.nvm/versions/node/v22.9.0/lib/node_modules/tldr/node_modules/adm-zip/adm-zip.js:62
            throw Utils.Errors.INVALID_FILENAME();
            ^

Error: ADM-ZIP: Invalid filename
    at Object.INVALID_FILENAME (/home/ttt/.nvm/versions/node/v22.9.0/lib/node_modules/tldr/node_modules/adm-zip/util/errors.js:56:16)
    at new module.exports (/home/ttt/.nvm/versions/node/v22.9.0/lib/node_modules/tldr/node_modules/adm-zip/adm-zip.js:62:32)
    at WriteStream.<anonymous> (/home/ttt/.nvm/versions/node/v22.9.0/lib/node_modules/tldr/lib/remote.js:32:21)
    at WriteStream.emit (node:events:531:35)
    at finish (node:internal/streams/writable:955:10)
    at node:internal/streams/writable:936:13
    at process.processTicksAndRejections (node:internal/process/task_queues:90:21)

Node.js v22.9.0
```

**Comment by agnivade** [comment]
I am unable to repro this. Using Node 20.11.1.

**Comment by shev85** [comment]
> Thanks for reporting the issue, can you try running `tldr --clear-cache` then run `tldr --update` to see if it fixes the issue?

Try `tldr --clear-cache` then run `tldr --update` , dosen't work，either.

**Comment by kbdharun** [comment]
Hi, Can you try running `npm uninstall -g tldr` then remove cache with `npm cache clean --force` then reinstall it using `npm install -g tldr`.

**Comment by LeDavid** [comment]
It seems that I have the same problem after a fresh install:

> Updating.../usr/lib/node_modules/tldr/node_modules/adm-zip/adm-zip.js:62
>             throw Utils.Errors.INVALID_FILENAME();
>             ^
> 
> Error: ADM-ZIP: Invalid filename
>     at Object.INVALID_FILENAME (/usr/lib/node_modules/tldr/node_modules/adm-zip/util/errors.js:56:16)
>     at new module.exports (/usr/lib/node_modules/tldr/node_modules/adm-zip/adm-zip.js:62:32)
>     at WriteStream.<anonymous> (/usr/lib/node_modules/tldr/lib/remote.js:32:21)
>     at WriteStream.emit (node:events:531:35)
>     at finish (node:internal/streams/writable:953:10)
>     at node:internal/streams/writable:934:13
>     at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
> 
> Node.js v20.18.0

I have tried all the solutions proposed above (uninstall, clear cache, etc.) but none of them solved the problem.

**Comment by kbdharun** [comment]
> It seems that I have the same problem after a fresh install:
> 
> > Updating.../usr/lib/node_modules/tldr/node_modules/adm-zip/adm-zip.js:62
> >             throw Utils.Errors.INVALID_FILENAME();
> >             ^
> > 
> > Error: ADM-ZIP: Invalid filename
> >     at Object.INVALID_FILENAME (/usr/lib/node_modules/tldr/node_modules/adm-zip/util/errors.js:56:16)
> >     at new module.exports (/usr/lib/node_modules/tldr/node_modules/adm-zip/adm-zip.js:62:32)
> >     at WriteStream.<anonymous> (/usr/lib/node_modules/tldr/lib/remote.js:32:21)
> >     at WriteStream.emit (node:events:531:35)
> >     at finish (node:internal/streams/writable:953:10)
> >     at node:internal/streams/writable:934:13
> >     at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
> > 
> > Node.js v20.18.0
> 
> I have tried all the solutions proposed above (uninstall, clear cache, etc.) but none of them solved the problem.

Hi, if possible can you clone the repository here with `git clone https://github.com/tldr-pages/tldr-node-client && cd tldr-node-client` then install the dependencies with `npm install` then try `./bin/tldr -u` to see if it fixes the issue and let me know.

If the issue is due to outdated dependencies, then it will be fixed when I make a new release with the updated deps from the main branch.

**Comment by LeDavid** [comment]
I did what you wrote and I got this error message:

```
Updating.../home/david/Tmp/tldr-node-client/node_modules/adm-zip/zipFile.js:123
        if (endOffset == -1) throw Utils.Errors.INVALID_FORMAT();
                             ^

Error: ADM-ZIP: Invalid or unsupported zip format. No END header found
    at Object.INVALID_FORMAT (/home/david/Tmp/tldr-node-client/node_modules/adm-zip/util/errors.js:56:16)
    at readMainHeader (/home/david/Tmp/tldr-node-client/node_modules/adm-zip/zipFile.js:123:49)
    at new module.exports (/home/david/Tmp/tldr-node-client/node_modules/adm-zip/zipFile.js:21:9)
    at new module.exports (/home/david/Tmp/tldr-node-client/node_modules/adm-zip/adm-zip.js:67:18)
    at WriteStream.<anonymous> (/home/david/Tmp/tldr-node-client/lib/remote.js:32:21)
    at WriteStream.emit (node:events:531:35)
    at finish (node:internal/streams/writable:953:10)
    at node:internal/streams/writable:934:13
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)

Node.js v20.18.0
```

I hope this would help you to find what happens.

**Comment by sunshinekao** [comment]
```
⠙ Updating.../usr/local/lib/node_modules/tldr/node_modules/adm-zip/adm-zip.js:62
            throw Utils.Errors.INVALID_FILENAME();
            ^

Error: ADM-ZIP: Invalid filename
    at Object.INVALID_FILENAME (/usr/local/lib/node_modules/tldr/node_modules/adm-zip/util/errors.js:56:16)
    at new module.exports (/usr/local/lib/node_modules/tldr/node_modules/adm-zip/adm-zip.js:62:32)
    at WriteStream.<anonymous> (/usr/local/lib/node_modules/tldr/lib/remote.js:32:21)
    at WriteStream.emit (node:events:536:35)
    at finish (node:internal/streams/writable:955:10)
    at node:internal/streams/writable:936:13
    at process.processTicksAndRejections (node:internal/process/task_queues:90:21)

Node.js v22.12.0
```
I seem to have encountered the same problem as well

**Comment by ZzddzZ2004** [comment]
I tried lots of times and failed, when i lost all hope and i tried the last time and succeed.Maybe you should try “sudo npm install -g tldr ” more times and "tldr list", at last "tldr --update", I believed it's a kind of bug.

**Comment by zimudec** [comment]
> I tried lots of times and failed, when i lost all hope and i tried the last time and succeed.Maybe you should try “sudo npm install -g tldr ” more times and "tldr list", at last "tldr --update", I believed it's a kind of bug.

If you are using "sudo", you are probably using npm without using nvm. I understand that the problem occurs using nvm.

I just tried the steps above, without success.

**Comment by TobiasNx** [comment]
I think I encountered the same problem. None of the suggested solutions seem to work.

```
$ tldr pandoc
⠙ Page not found. Updating cache.../home/usr/.nvm/versions/node/v23.9.0/lib/node_modules/tldr/node_modules/adm-zip/adm-zip.js:62
            throw Utils.Errors.INVALID_FILENAME();
            ^

Error: ADM-ZIP: Invalid filename
    at Object.INVALID_FILENAME (/home/usr/.nvm/versions/node/v23.9.0/lib/node_modules/tldr/node_modules/adm-zip/util/errors.js:56:16)
    at new module.exports (/home/usr/.nvm/versions/node/v23.9.0/lib/node_modules/tldr/node_modules/adm-zip/adm-zip.js:62:32)
    at WriteStream.<anonymous> (/home/usr/.nvm/versions/node/v23.9.0/lib/node_modules/tldr/lib/remote.js:32:21)
    at WriteStream.emit (node:events:519:35)
    at finish (node:internal/streams/writable:953:10)
    at node:internal/streams/writable:934:13
    at process.processTicksAndRejections (node:internal/process/task_queues:90:21)

Node.js v23.9.0
```

**Comment by escapetts** [comment]
I encountered the same issue with the npm installation. Unstalled it and installed with the tldr python client and it works as expected:
sudo npm uninstall -g tldr
pip install tldr
export PATH="$PATH/<tldr installation path>"

**Comment by Mike-7** [comment]
In file lib/config.js
Line 50 should be changed from
```
merged.languages.push(...langs.map((lang) => {
  return utils.localeToLang(lang);
}));
```
to
```
merged.languages.push(...langs.flatMap((lang) => {
  return utils.localeToLang(lang);
}));
```
Array value:
merged.languages = [ 'en', 'localeFromLANG', ['localeFromLANGUAGE'] ] // original code
merged.languages = [ 'en', 'localeFromLANG', 'localeFromLANGUAGE' ] // fixed code
